/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue')['AAlert']
    AButton: typeof import('ant-design-vue')['AButton']
    ACard: typeof import('ant-design-vue')['ACard']
    ADivider: typeof import('ant-design-vue')['ADivider']
    AInput: typeof import('ant-design-vue')['AInput']
    ASelect: typeof import('ant-design-vue')['ASelect']
    ASelectOption: typeof import('ant-design-vue')['ASelectOption']
    ASpace: typeof import('ant-design-vue')['ASpace']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
